local library = loadstring(game:HttpGet("https://raw.githubusercontent.com/DashaBars/Hack/main/Gui"))()
local window1 = library:Window("Teleports")

library:Keybind("Q")

local vu = game:GetService("VirtualUser")
game:GetService("Players").LocalPlayer.Idled:connect(function()
vu:Button2Down(Vector2.new(0,0),workspace.CurrentCamera.CFrame)
wait(1)
vu:Button2Up(Vector2.new(0,0),workspace.CurrentCamera.CFrame)
end)

window1:Button('Noob Island', function()
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new (-6277, 80, 8501)
end)
window1:Button('Sand Canyons', function()
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new (55807, 82, -10131)
end)
window1:Button('Icy Planes', function()
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new (-16365, 85, -3623)
end)
window1:Button('Magma Hills', function()
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new (-11571, 110, -17811)
end)
window1:Button('Poisoned Cove', function()
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new (11191, 96, -28292)
end)